#!/usr/bin/env python3
"""PostToolUse hook -- CARD-0334 Phase 1c, step 2 of 2.

Runs AFTER a tool call completes. Can't un-print something that already
leaked -- the point is ending silent exposure by flagging it immediately
instead of it sitting unnoticed in a transcript, which is exactly how this
session's own Fourth occurrence (2026-10-02) stayed unnoticed for as long as
it did tonight.

Reads tos/hooks/secret-fingerprints.json + .secret-salt (generated by
generate-fingerprints.py, run by Joseph, never committed -- see that script's
own docstring). For every distinct fingerprinted length, slides a window of
that exact length across the tool's output, salts+hashes each window, and
checks it against the known fingerprint set. A hit means a real secret value
just appeared in output -- flagged by name-of-length-and-hash only (never the
value, which this hook never actually possesses) so even the alert can't leak
anything further.

NOT YET LIVE-VERIFIED -- same caveat as the PreToolUse guard. Fails OPEN if
the fingerprints file doesn't exist yet (nothing to compare against) or can't
be parsed, rather than blocking every tool call because of a missing file.
"""
import hashlib
import json
import os
import sys

HOOKS_DIR = os.path.dirname(os.path.abspath(__file__))
SALT_FILE = os.path.join(HOOKS_DIR, ".secret-salt")
FINGERPRINTS_FILE = os.path.join(HOOKS_DIR, "secret-fingerprints.json")


def load_fingerprints():
    if not (os.path.exists(SALT_FILE) and os.path.exists(FINGERPRINTS_FILE)):
        return None, None
    with open(SALT_FILE, "r") as f:
        salt = f.read().strip()
    with open(FINGERPRINTS_FILE, "r") as f:
        entries = json.load(f)
    by_length = {}
    for e in entries:
        by_length.setdefault(e["length"], set()).add(e["hash"])
    return salt, by_length


def scan(text, salt, by_length):
    for length, hashes in by_length.items():
        if len(text) < length:
            continue
        for i in range(len(text) - length + 1):
            window = text[i:i + length]
            digest = hashlib.sha256((salt + window).encode("utf-8", errors="ignore")).hexdigest()
            if digest in hashes:
                return length
    return None


def extract_output_text(payload):
    result = payload.get("tool_response") or payload.get("tool_result") or {}
    parts = []
    if isinstance(result, dict):
        for key in ("stdout", "output", "content", "text"):
            value = result.get(key)
            if isinstance(value, str):
                parts.append(value)
    elif isinstance(result, str):
        parts.append(result)
    return "\n".join(parts)


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        sys.exit(0)

    salt, by_length = load_fingerprints()
    if salt is None:
        sys.exit(0)  # no fingerprints generated yet -- nothing to check against

    text = extract_output_text(payload)
    if not text:
        sys.exit(0)

    hit_length = scan(text, salt, by_length)
    if hit_length is not None:
        tool_name = payload.get("tool_name", "unknown tool")
        print(
            f"INCIDENT: {tool_name}'s output just matched a known secret's "
            f"fingerprint (a {hit_length}-character value). A real credential "
            f"was likely just printed. Stop, name the credential (never the "
            f"value) on the relevant card, and treat it as exposed -- same "
            f"discipline as CARD-0334's prior occurrences.",
            file=sys.stderr,
        )
        sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
    main()
