services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    volumes:
      - /home/pi/homeassistant:/config
    restart: unless-stopped
    privileged: true
    security_opt:
      - label:disable
    environment:
      - TZ=America/Phoenix
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/manifest.json"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s
